### ISSUE TITLE
URL routing problem

### ISSUE THREAD

**Issue by emaadali** [BC-CTE/CTE-Cohort-Scheduler#1]
Using `idesstage2.bc.edu/cohortscheduler/public` works fine (although you need to map `/public` to be the virtual directory), but `http://ctecohorts.bc.edu/` doesn't work. 

`http://ctecohorts.bc.edu/` will load the sign in route just fine, but will not load `/dashboard` or any other route.

**Comment by walkerjamie** [comment]
looking at the .htaccess file and httpd.conf now

**Comment by walkerjamie** [comment]
The app root directory needed allowoverides all to give mod_rewrite and .htaccess file the permissions to run from there. This is done in the httpd.conf <directory> directive for the assigned vhost.
